# Site settings
title: Kai Zhang
description: 'EARNED NOT GIVEN / I AM ALWAYS READY TO ACCEPT CHALLENGE.'
url: 'https://1146976048qq.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Kai Zhang'
  email: sa517494@mail.ustc.edu.cn
  # facebook: im_Not
  twitter_username: zhangyooo
  # facebook_username: zhangyoooo
  github_username:  1146976048qq
  # linkedin_username:  Kai Zhang

# Social
social:
  weibo: /u/3064614765?is_all=1
  gplus: 101428651377493282857


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
